#!/usr/bin/env bash
#my live-server wrapper

function run() {
  if which npx &>/dev/null; then
    npx live-server ${@:1} #pass all arguments starting at 1
  else
    echo "npx not found ! Make sure node is installed and available to current user !"
  fi
}

if [ "$1" = "-h" ]; then
  echo "Usage: "
  echo "./start <args>  : start live-server and pass args to it"
  echo "./start -p 1234 : start live-server on port 1234"
elif [ "$1" = "-p" ] && [ ! -z "$2" ]; then
  run --port=$2
elif [ ! -z $1 ]; then
  run ${@:1}
else
  run --port=8080
fi
